### ISSUE TITLE
Опечатка в слове украинсокм

### ISSUE THREAD

**Issue by artshishkin** [Katerina-shysh/QA-study#1]
Исправить опечатку во фразе [`Баг - Наименования некоторых товаров на украинсокм языке.`](https://github.com/Katerina-shysh/QA-study/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%203_%D0%A7%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82/%D0%A7%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82_%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_https___www.yakaboo.ua_%20-%20%D0%9B%D0%B8%D1%81%D1%821.csv)

**Comment by Katerina-shysh** [comment]
https://github.com/Katerina-shysh/QA-study/commit/eb3731761d9cf7e84c9b31bf18d552b7aecc4ec7

**Comment by artshishkin** [comment]
Ты молодец! Все ОК
